### ISSUE TITLE
Creacion de Modulos

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/restApi-ci-itgam#30]
## Requisitos del Issue: Organización de Módulos y Rutas

**Objetivo:**
El objetivo de este issue es organizar la estructura de la aplicación separando las responsabilidades y creando rutas para los módulos "home" y "error". Además, se debe adaptar el archivo `src/routes.js` para que funcione correctamente con estos cambios.

**Tareas a Realizar:**

1. Crear una nueva carpeta llamada `modules` dentro del directorio `./src`. Esta carpeta se utilizará para separar las responsabilidades de la aplicación.

2. Dentro de la carpeta `./src/modules`, crear dos subdirectorios: `home` y `error`. Estos directorios albergarán los archivos relacionados con los módulos correspondientes.

3. En el directorio `./src/modules/home`, se deben colocar los siguientes archivos:

   - `home.route.js`: Este archivo será responsable de gestionar la conexión de las rutas "/" con su respectivo controlador.
   
   - `home.controller.js`: En este archivo se definirá el controlador del módulo "home", incluyendo sus métodos de acción correspondientes.

4. En el directorio `./src/modules/error`, se debe colocar el archivo:

   - `error.controller.js`: Este archivo exportará las funciones `error404(req, res)` y `generalError(err, req, res, next)`. Estas funciones contendrán el código para manejar los errores 404 y los errores de tipo 500. Estas funciones se exportarán y se encadenarán al sistema de middlewares en el archivo `src/routes.js`.

5. Se requiere adaptar el archivo `src/routes.js` para asegurar que las rutas de los módulos "home" y "error" sean enrutadas correctamente. Debe utilizarse la lógica adecuada para llamar a los controladores y manejar los errores de acuerdo con las funciones definidas en los archivos mencionados anteriormente.

**Nota:**
Asegúrate de que los archivos y rutas estén configurados de manera coherente y sigan las mejores prácticas de desarrollo. Asegúrate también de que la estructura de carpetas y archivos sea consistente con la organización de módulos propuesta.

Por favor, sigue estos requisitos para llevar a cabo la tarea y asegúrate de que la implementación sea coherente con la descripción dada.

**Comment by Fabiolaolmos** [comment]
@rivalcoba Listo quedo pendiente ante cualquier observación
