### ISSUE TITLE
Proponer un README

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/restApi-ci-itgam#4]
Actualmente el proyecto tiene un [README](https://github.com/rivalcoba/restApi-ci-itgam/blob/main/README.md) que fue creado por el generador, crear la propuesta de un Readme que contenga información del proyecto, imagen institucional, los objetivos generales y específicos.

**Comment by rivalcoba** [comment]
@Fabiolaolmos ya te he creado una Rama para que resulevas este issue, como veras el nombre de la rama tiene que ver con el nombre del issue, la rama de este issue que he creado lo puedes consultar [aqui](https://github.com/rivalcoba/restApi-ci-itgam/tree/4-proponer-un-readme)

**Comment by Fabiolaolmos** [comment]
@rivalcoba hola profe tuve una complicación en subir los cambios ya que no me deja hacer el pull, si me podria orientar ya que estuve buscando soluciones y no se pudo realizar.

**Comment by Fabiolaolmos** [comment]
@rivalcoba Listo
