### ISSUE TITLE
Carpeta dedicada al Backend

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/restApi-ci-itgam#5]
# Instrucciones

1. Mueve todo el código relacionado al backend a un directorio llamado `./src`.
2. Asegúrate de que el directorio `public` permanezca en la raíz del proyecto, ya que no forma parte del backend propiamente dicho.
3. Realiza los cambios necesarios en los archivos y configuraciones para que el proyecto siga funcionando correctamente después de haber movido el código a la carpeta `./src`.

**Comment by Fabiolaolmos** [comment]
Entendido

**Comment by Fabiolaolmos** [comment]
Listo profe ya realice lo asignado

**Comment by rivalcoba** [comment]
@Fabiolaolmos Sigo a la espera de que concluyas este issue, no has solicitado pull request. Debio haber quedado para el 14 de Julio estas ya fuera de tiempo, ¿Hay algun problema?

**Comment by Fabiolaolmos** [comment]
@rivalcoba listo realice la modificación

**Comment by rivalcoba** [comment]
@Fabiolaolmos aun sigue sin moverse este issue, urge que ya lo saques para el viernes o lo reasignare.

**Comment by Fabiolaolmos** [comment]
@rivalcoba Listo
