### ISSUE TITLE
Babel Tranpiler

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/restApi-ci-itgam#6]
# Instrucciones

Incorporar [Babel](https://babeljs.io/) al proyecto utilizando el preset [@babel/preset-env](https://babeljs.io/docs/babel-preset-env) y como target la versión de Node actual o **current**.

Crear un script llamado `dev` que use  a [babel-watch](https://www.npmjs.com/package/babel-watch) para ejecutar la aplicación.

Crear un script llamado  `clean` que borre un directorio llamado `dist`.

Crear un script llamado `build` que ejecute el script `clean`y despues construya la aplicación en un directorio llamado `dist`

**Comment by PamRios** [comment]
@rivalcoba Creados los scripts, las instalaciones ya estaban hechas por lo que solo he creado los scripts
https://github.com/rivalcoba/restApi-ci-itgam/tree/53e52a2562b8b8a0da546c7a58c95918f53f3ba6

**Comment by rivalcoba** [comment]
@PamRios lo trabajaste desde una rama cerrada, la rama en que lo debes de trabajar [es esta](https://github.com/rivalcoba/restApi-ci-itgam/tree/6-babel-tranpiler-1) ya que la que la rama [cerrada](https://github.com/rivalcoba/restApi-ci-itgam/tree/6-babel-tranpiler) es una que trabajo @Fabiolaolmos y no esta actualizada, favor de realizar lo propio en la rama correcta.

**Comment by PamRios** [comment]
@rivalcoba Hecho lo propio en la rama indicada https://github.com/rivalcoba/restApi-ci-itgam/tree/a1fcbb0c94b0810013258916b62aa307f8b6ff56

**Comment by rivalcoba** [comment]
@PamRios Debes solicitar el PullRequest siempre que termines un Issue para que proceda con la revisión, te pido hagas el pullrequest y me asignes como revisor, Fabiola ya lo sabe hacer si no te acuerdas como.
